import {
    QuizInclude,
    QuizOmit,
    QuizSelect,
    QuizStatus,
} from '../types/quiz.domain';
import { KeysArray } from '#types';

export const QUIZ_OMIT: KeysArray<QuizOmit> = [
    'id',
    'title',
    'visibility',
    'status',
    'coverImage',
    'tagsIds',
    'languagesIds',
    'shuffleAnswers',
    'shuffleQuestions',
    'subjectId',
    'createdAt',
    'updatedAt',
    'favouritedByIds',
    'createdById',
    'copiedByIds',
    'completedByIds',
    'folderIds',
];
export const QUIZ_SELECT: KeysArray<QuizSelect> = [
    'id',
    'title',
    'visibility',
    'status',
    'coverImage',
    'tagsIds',
    'languagesIds',
    'shuffleAnswers',
    'shuffleQuestions',
    'subjectId',
    'createdAt',
    'updatedAt',
    'favouritedByIds',
    'createdById',
    'copiedByIds',
    'completedByIds',
    'folderIds',
    'subject',
    'languages',
    'completedBy',
    'copiedBy',
    'createdBy',
    'favouritedBy',
    'folders',
    'questions',
    'tags',
];

export const QUIZ_INCLUDE: KeysArray<QuizInclude> = [
    '_count',
    'attempted',
    'completedBy',
    'copiedBy',
    'createdBy',
    'favouritedBy',
    'folders',
    'languages',
    'questions',
    'rooms',
    'subject',
    'tags',
];
export const QUIZ_STATUS: QuizStatus[] = ['PUBLISHED', 'DRAFT'];

export const QUIZ_COPY_SELECT = {
    questions: true,
    title: true,
    subjectId: true,
    tagsIds: true,
    languagesIds: true,
    shuffleAnswers: true,
    shuffleQuestions: true,
    visibility: true,
    coverImage: true,
};
